// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTqU2Wko32O3QO773geObjqGvJPE6i31E',
    appId: '1:62096819076:web:67d8c71bbea9f0c61b93d1',
    messagingSenderId: '62096819076',
    projectId: 'eixoone-dev',
    authDomain: 'eixoone-dev.firebaseapp.com',
    storageBucket: 'eixoone-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWm4OmDI-AuPwWESodDWswXd9o-Z3Knw',
    appId: '1:62096819076:android:f632f52f19a5a9ed1b93d1',
    messagingSenderId: '62096819076',
    projectId: 'eixoone-dev',
    storageBucket: 'eixoone-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMtRLzU4RvhOq1GmedZGYKRFWlcamiwdY',
    appId: '1:62096819076:ios:9ab33567d1a5dc381b93d1',
    messagingSenderId: '62096819076',
    projectId: 'eixoone-dev',
    storageBucket: 'eixoone-dev.firebasestorage.app',
    iosBundleId: 'com.eixoone.eixooneMobile',
  );

}